database:
  path: "data/analytics.db"

forexfactory:
  url: "https://www.forexfactory.com/calendar"
  currency: "USD"
  events:
    - "CPI y/y"
    - "CPI m/m"
    - "PPI m/m"
    - "Core PCE Price Index m/m"
    - "GDP"
    - "Non-Farm Employment Change"
    - "Unemployment Rate"
    - "ISM Manufacturing PMI"
    - "ISM Services PMI"
    - "Retail Sales"
    - "FOMC"
    - "Federal Reserve"
    - "Jackson Hole"
    - "Bank Holiday"

fomc:
  url: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm"
  statement_selector: "div.col-xs-12.col-sm-8.col-md-8" 
  xPath: /html/body/div[7]/div[2]/div/div[3]

markets:
  symbols:
    - "^TNX"
    - "DX-Y.NYB"
    - "BTC-USD"
    - "GC=F"
    - "CL=F"
    - "ES=F"
  range_days: 30

logging:
  level: "INFO"
  file: "app.log"